# Generated by Django 3.1 on 2020-08-08 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20200808_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityperiodmodel',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='API.usermodel'),
        ),
    ]
